pipeline:
  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-python
    dockerfile: ./2.7/Dockerfile
    tag:
      - '2.7'
    when:
      branch:
        include: [ '2.7' ]
    force_tag: true

#publish:
#  docker:
#    repo: registry.liskl.com/tstllc/alpine-ftp
#    tag:
#      - latest
#    when:
#      branch:
#        include: [ master, release/* ]

#publish:
#  docker:
#    repo: registry.liskl.com/tstllc/alpine-ftp
#    tag:
#      - ${DRONE_BRANCH}-latest
#      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
#    when:
#      branch:
#        exclude: [ master ]
