pipeline:
  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-python
    dockerfile: ./2.7/Dockerfile
    context: ./2.7/
    tag:
      - '2.7'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-python
    dockerfile: ./2.7-slim/Dockerfile
    context: ./2.7-slim/
    tag:
      - '2.7-slim'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-python
    dockerfile: ./3.4/Dockerfile
    context: ./3.4/
    tag:
      - '3.4'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.liskl.com/tstllc/alpine-python
    dockerfile: ./3.4-slim/Dockerfile
    context: ./3.4-slim/
    tag:
      - '3.4-slim'
    force_tag: true

publish:
  docker:
    repo: registry.liskl.com/tstllc/alpine-python
    tag:
#      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master, 2.7, 2.7-slim, 3.4, 3.4-slim ]
