pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-python
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
    dockerfile: ./2.7/Dockerfile
    context: ./2.7/
    tag:
      - '2.7'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-python
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net

    dockerfile: ./2.7-slim/Dockerfile
    context: ./2.7-slim/
    tag:
      - '2.7-slim'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-python
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
    dockerfile: ./3.4/Dockerfile
    context: ./3.4/
    tag:
      - '3.4'
    force_tag: true

  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-python
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
    dockerfile: ./3.4-slim/Dockerfile
    context: ./3.4-slim/
    tag:
      - '3.4-slim'
    force_tag: true

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-python
    username: ${REPO_USERNAME}
    password: ${REPO_PASSWORD}
    email: ${REPO_EMAILADDR}
    registry: registry.tstllc.net
    tag:
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master, 2.7, 2.7-slim, 3.4, 3.4-slim ]
